# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consistency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consistency.proto',
  package='consistency',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63onsistency.proto\x12\x0b\x63onsistency\"\x06\n\x04Void\"\x17\n\x06RValue\x12\r\n\x05value\x18\x01 \x01(\x03\")\n\tInputData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\x03\"\x16\n\x03Map\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"0\n\x0eMapDataRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x03\"\"\n\x11ReduceDataRequest\x12\r\n\x05index\x18\x01 \x01(\x03\"0\n\x0eMapRegResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05index\x18\x02 \x01(\x03\"\x19\n\x06Reduce\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"3\n\x11ReduceRegResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05index\x18\x02 \x01(\x03\".\n\x10IntermediateData\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x03(\x03\"\'\n\tFinalData\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x03(\x03\x32\xc2\x01\n\nMaster_Map\x12\x45\n\x0cgetInputData\x12\x1b.consistency.MapDataRequest\x1a\x16.consistency.InputData\"\x00\x12;\n\x08Register\x12\x10.consistency.Map\x1a\x1b.consistency.MapRegResponse\"\x00\x12\x30\n\x04getR\x12\x11.consistency.Void\x1a\x13.consistency.RValue\"\x00\x32\x64\n\nMap_Reduce\x12V\n\x13getIntermediateData\x12\x1e.consistency.ReduceDataRequest\x1a\x1d.consistency.IntermediateData\"\x00\x32\x90\x01\n\rMaster_Reduce\x12\x41\n\x08Register\x12\x13.consistency.Reduce\x1a\x1e.consistency.ReduceRegResponse\"\x00\x12<\n\x11getRegisteredMaps\x12\x11.consistency.Void\x1a\x10.consistency.Map\"\x00\x30\x01\x32L\n\rReduce_Master\x12;\n\x0cgetFinalData\x12\x11.consistency.Void\x1a\x16.consistency.FinalData\"\x00\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='consistency.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=40,
)


_RVALUE = _descriptor.Descriptor(
  name='RValue',
  full_name='consistency.RValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='consistency.RValue.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=65,
)


_INPUTDATA = _descriptor.Descriptor(
  name='InputData',
  full_name='consistency.InputData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='consistency.InputData.data', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doc_id', full_name='consistency.InputData.doc_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=108,
)


_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='consistency.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='consistency.Map.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=132,
)


_MAPDATAREQUEST = _descriptor.Descriptor(
  name='MapDataRequest',
  full_name='consistency.MapDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='consistency.MapDataRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='consistency.MapDataRequest.index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=182,
)


_REDUCEDATAREQUEST = _descriptor.Descriptor(
  name='ReduceDataRequest',
  full_name='consistency.ReduceDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='consistency.ReduceDataRequest.index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=218,
)


_MAPREGRESPONSE = _descriptor.Descriptor(
  name='MapRegResponse',
  full_name='consistency.MapRegResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='consistency.MapRegResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='consistency.MapRegResponse.index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=268,
)


_REDUCE = _descriptor.Descriptor(
  name='Reduce',
  full_name='consistency.Reduce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='consistency.Reduce.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=295,
)


_REDUCEREGRESPONSE = _descriptor.Descriptor(
  name='ReduceRegResponse',
  full_name='consistency.ReduceRegResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='consistency.ReduceRegResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='consistency.ReduceRegResponse.index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=348,
)


_INTERMEDIATEDATA = _descriptor.Descriptor(
  name='IntermediateData',
  full_name='consistency.IntermediateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='consistency.IntermediateData.key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='consistency.IntermediateData.value', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=396,
)


_FINALDATA = _descriptor.Descriptor(
  name='FinalData',
  full_name='consistency.FinalData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='consistency.FinalData.key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='consistency.FinalData.value', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=437,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['RValue'] = _RVALUE
DESCRIPTOR.message_types_by_name['InputData'] = _INPUTDATA
DESCRIPTOR.message_types_by_name['Map'] = _MAP
DESCRIPTOR.message_types_by_name['MapDataRequest'] = _MAPDATAREQUEST
DESCRIPTOR.message_types_by_name['ReduceDataRequest'] = _REDUCEDATAREQUEST
DESCRIPTOR.message_types_by_name['MapRegResponse'] = _MAPREGRESPONSE
DESCRIPTOR.message_types_by_name['Reduce'] = _REDUCE
DESCRIPTOR.message_types_by_name['ReduceRegResponse'] = _REDUCEREGRESPONSE
DESCRIPTOR.message_types_by_name['IntermediateData'] = _INTERMEDIATEDATA
DESCRIPTOR.message_types_by_name['FinalData'] = _FINALDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.Void)
  ))
_sym_db.RegisterMessage(Void)

RValue = _reflection.GeneratedProtocolMessageType('RValue', (_message.Message,), dict(
  DESCRIPTOR = _RVALUE,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.RValue)
  ))
_sym_db.RegisterMessage(RValue)

InputData = _reflection.GeneratedProtocolMessageType('InputData', (_message.Message,), dict(
  DESCRIPTOR = _INPUTDATA,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.InputData)
  ))
_sym_db.RegisterMessage(InputData)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), dict(
  DESCRIPTOR = _MAP,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.Map)
  ))
_sym_db.RegisterMessage(Map)

MapDataRequest = _reflection.GeneratedProtocolMessageType('MapDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPDATAREQUEST,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.MapDataRequest)
  ))
_sym_db.RegisterMessage(MapDataRequest)

ReduceDataRequest = _reflection.GeneratedProtocolMessageType('ReduceDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _REDUCEDATAREQUEST,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.ReduceDataRequest)
  ))
_sym_db.RegisterMessage(ReduceDataRequest)

MapRegResponse = _reflection.GeneratedProtocolMessageType('MapRegResponse', (_message.Message,), dict(
  DESCRIPTOR = _MAPREGRESPONSE,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.MapRegResponse)
  ))
_sym_db.RegisterMessage(MapRegResponse)

Reduce = _reflection.GeneratedProtocolMessageType('Reduce', (_message.Message,), dict(
  DESCRIPTOR = _REDUCE,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.Reduce)
  ))
_sym_db.RegisterMessage(Reduce)

ReduceRegResponse = _reflection.GeneratedProtocolMessageType('ReduceRegResponse', (_message.Message,), dict(
  DESCRIPTOR = _REDUCEREGRESPONSE,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.ReduceRegResponse)
  ))
_sym_db.RegisterMessage(ReduceRegResponse)

IntermediateData = _reflection.GeneratedProtocolMessageType('IntermediateData', (_message.Message,), dict(
  DESCRIPTOR = _INTERMEDIATEDATA,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.IntermediateData)
  ))
_sym_db.RegisterMessage(IntermediateData)

FinalData = _reflection.GeneratedProtocolMessageType('FinalData', (_message.Message,), dict(
  DESCRIPTOR = _FINALDATA,
  __module__ = 'consistency_pb2'
  # @@protoc_insertion_point(class_scope:consistency.FinalData)
  ))
_sym_db.RegisterMessage(FinalData)



_MASTER_MAP = _descriptor.ServiceDescriptor(
  name='Master_Map',
  full_name='consistency.Master_Map',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=440,
  serialized_end=634,
  methods=[
  _descriptor.MethodDescriptor(
    name='getInputData',
    full_name='consistency.Master_Map.getInputData',
    index=0,
    containing_service=None,
    input_type=_MAPDATAREQUEST,
    output_type=_INPUTDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='consistency.Master_Map.Register',
    index=1,
    containing_service=None,
    input_type=_MAP,
    output_type=_MAPREGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getR',
    full_name='consistency.Master_Map.getR',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_RVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER_MAP)

DESCRIPTOR.services_by_name['Master_Map'] = _MASTER_MAP


_MAP_REDUCE = _descriptor.ServiceDescriptor(
  name='Map_Reduce',
  full_name='consistency.Map_Reduce',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=636,
  serialized_end=736,
  methods=[
  _descriptor.MethodDescriptor(
    name='getIntermediateData',
    full_name='consistency.Map_Reduce.getIntermediateData',
    index=0,
    containing_service=None,
    input_type=_REDUCEDATAREQUEST,
    output_type=_INTERMEDIATEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAP_REDUCE)

DESCRIPTOR.services_by_name['Map_Reduce'] = _MAP_REDUCE


_MASTER_REDUCE = _descriptor.ServiceDescriptor(
  name='Master_Reduce',
  full_name='consistency.Master_Reduce',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=739,
  serialized_end=883,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='consistency.Master_Reduce.Register',
    index=0,
    containing_service=None,
    input_type=_REDUCE,
    output_type=_REDUCEREGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getRegisteredMaps',
    full_name='consistency.Master_Reduce.getRegisteredMaps',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_MAP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER_REDUCE)

DESCRIPTOR.services_by_name['Master_Reduce'] = _MASTER_REDUCE


_REDUCE_MASTER = _descriptor.ServiceDescriptor(
  name='Reduce_Master',
  full_name='consistency.Reduce_Master',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=885,
  serialized_end=961,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFinalData',
    full_name='consistency.Reduce_Master.getFinalData',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_FINALDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDUCE_MASTER)

DESCRIPTOR.services_by_name['Reduce_Master'] = _REDUCE_MASTER

# @@protoc_insertion_point(module_scope)
