# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consistency.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onsistency.proto\x12\x0b\x63onsistency\"\x06\n\x04Void\"\x17\n\x06RValue\x12\r\n\x05value\x18\x01 \x01(\x03\"\x19\n\tInputData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"\x16\n\x03Map\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"0\n\x0eMapDataRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x03\"\"\n\x11ReduceDataRequest\x12\r\n\x05index\x18\x01 \x01(\x03\"0\n\x0eMapRegResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05index\x18\x02 \x01(\x03\"\x19\n\x06Reduce\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"3\n\x11ReduceRegResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05index\x18\x02 \x01(\x03\" \n\x10IntermediateData\x12\x0c\n\x04path\x18\x01 \x01(\t\"\'\n\tFinalData\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x03(\x03\x32\xc2\x01\n\nMaster_Map\x12\x45\n\x0cgetInputData\x12\x1b.consistency.MapDataRequest\x1a\x16.consistency.InputData\"\x00\x12;\n\x08Register\x12\x10.consistency.Map\x1a\x1b.consistency.MapRegResponse\"\x00\x12\x30\n\x04getR\x12\x11.consistency.Void\x1a\x13.consistency.RValue\"\x00\x32\x64\n\nMap_Reduce\x12V\n\x13getIntermediateData\x12\x1e.consistency.ReduceDataRequest\x1a\x1d.consistency.IntermediateData\"\x00\x32\x90\x01\n\rMaster_Reduce\x12\x41\n\x08Register\x12\x13.consistency.Reduce\x1a\x1e.consistency.ReduceRegResponse\"\x00\x12<\n\x11getRegisteredMaps\x12\x11.consistency.Void\x1a\x10.consistency.Map\"\x00\x30\x01\x32L\n\rReduce_Master\x12;\n\x0cgetFinalData\x12\x11.consistency.Void\x1a\x16.consistency.FinalData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consistency_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=34
  _VOID._serialized_end=40
  _RVALUE._serialized_start=42
  _RVALUE._serialized_end=65
  _INPUTDATA._serialized_start=67
  _INPUTDATA._serialized_end=92
  _MAP._serialized_start=94
  _MAP._serialized_end=116
  _MAPDATAREQUEST._serialized_start=118
  _MAPDATAREQUEST._serialized_end=166
  _REDUCEDATAREQUEST._serialized_start=168
  _REDUCEDATAREQUEST._serialized_end=202
  _MAPREGRESPONSE._serialized_start=204
  _MAPREGRESPONSE._serialized_end=252
  _REDUCE._serialized_start=254
  _REDUCE._serialized_end=279
  _REDUCEREGRESPONSE._serialized_start=281
  _REDUCEREGRESPONSE._serialized_end=332
  _INTERMEDIATEDATA._serialized_start=334
  _INTERMEDIATEDATA._serialized_end=366
  _FINALDATA._serialized_start=368
  _FINALDATA._serialized_end=407
  _MASTER_MAP._serialized_start=410
  _MASTER_MAP._serialized_end=604
  _MAP_REDUCE._serialized_start=606
  _MAP_REDUCE._serialized_end=706
  _MASTER_REDUCE._serialized_start=709
  _MASTER_REDUCE._serialized_end=853
  _REDUCE_MASTER._serialized_start=855
  _REDUCE_MASTER._serialized_end=931
# @@protoc_insertion_point(module_scope)
